### ISSUE TITLE
Crear ramas y revisar

### ISSUE THREAD

**Issue by MilagroCorrea** [xX-RONIN-Xx/TP_TIO#3]
Crear una rama cada uno, hacer modificaciones y fusionarlas.

**Comment by xX-RONIN-Xx** [comment]
@MilagroCorrea Ya creé la rama, modique estilo.css en logo y subi mis cambios.

**Comment by MilagroCorrea** [comment]
Creé la rama cambios_estilo y subí los cambios realizados.

**Comment by MilagroCorrea** [comment]
Aparentemente todo ok!

**Comment by MilagroCorrea** [comment]
Cada uno creó dos ramas y ya están revisadas. Cierro esta Issue.
