### ISSUE TITLE
Conflicto en index.html

### ISSUE THREAD

**Issue by xX-RONIN-Xx** [xX-RONIN-Xx/TP_TIO#5]
@MilagroCorrea Noté que cambiaste la imagen en index y su texto alternativo. trabajé sobre la misma linea. Estas segura de dejar la imagen del honguito y su alt?

**Comment by MilagroCorrea** [comment]
Si, que queden las modificaciones que yo realicé. Gracias por avisar!

**Comment by MilagroCorrea** [comment]
@xX-RONIN-Xx  fijate porfa.

**Comment by xX-RONIN-Xx** [comment]
Ok, dejo la issue abierta para que la vean los profes

**Comment by xX-RONIN-Xx** [comment]
Solucionado el index.html. Cierro porque aprendimos que se pueden ver en la pestaña closed :)
